
###
POST {{url}}/api/products
Content-Type: application/json

{
  "name": "카카오 무지 인형",
  "price": 3000,
  "imageUrl": "https://example.com/image.jpg"
}

###
GET {{url}}/api/products
Content-Type: application/json

###
GET {{url}}/api/products/{{id}}

###
PUT {{url}}/api/products/{{id}}
Content-Type: application/json

{
  "name": "카카오 무지 인형",
  "price": 3500,
  "imageUrl": "https://example.com/image-updated.jpg"
}

###
DELETE {{url}}/api/products/{{id}}